zh_cn = {
    "home": "主页",
    "list": "模组列表",
    "docs": "文档",
    "admin": "管理",
    "AMM": "冰与火之舞模组管理器",
    "Adofai Mod Manager": "冰与火之舞模组管理器",
    "HTTP Error": "错误",
    "Admin Page": "管理员页面",
    "URL expired": "链接失效",
    "The URL of this map is expired.":"此铺面的下载链接已经失效。",
    "Mod Info":"模组详情",
    "Name":"模组名称",
    "Author":"作者",
    "Download Number": "下载数量",
    "Description": "简介",
    "Latest Version": "最新版本",
    "DownloadURL": "下载链接",
    "Click to download": "点击下载",
    "More Info": "详情",
    "Login": "登录",
    "Loading": "加载中",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}
